version: '3.6'

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK_PRIVATE}

services:
  odoo12:
    tty: true
    stdin_open: true
    build:
      args:
      - DOCKER_BUILD_DIR=docker/odoo
      - TARGET=${DOCKER_BUILD_TARGET}
      context: ..
      dockerfile: docker/odoo/Dockerfile
      target: ${DOCKER_BUILD_TARGET}
    environment:
    - ADDITIONAL_ODOO_RC=${ODOO12_ADDITIONAL_ODOO_RC}
    - ADDONS_PATH=${ODOO12_ADDONS_PATH}
    - ADMIN_PASSWD=${ODOO12_ADMIN_PASSWD}
    - DB_HOST=${ODOO12_DB_HOST}
    - DB_NAME=${ODOO12_DB_NAME}
    - DB_PASSWORD=${ODOO12_DB_PASS}
    - DB_USER=${ODOO12_DB_USER}
    - ELASTIC_APM_SERVER_URL=${ODOO12_ELASTIC_APM_SERVER_URL}
    - ELASTIC_APM_VERIFY_SERVER_CERT=${ODOO12_ELASTIC_APM_VERIFY_SERVER_CERT}
    - LOG_HANDLER=${ODOO12_LOG_HANDLER}
    - LOG_DB=${ODOO12_LOG_DB}
    - LOGFILE=${ODOO12_LOGFILE}
    - LOG_LEVEL=${ODOO12_LOG_LEVEL}
    - MARABUNTA_ALLOW_SERIE=${ODOO12_MARABUNTA_ALLOW_SERIE}
    - MARABUNTA_FORCE_VERSION=${ODOO12_MARABUNTA_FORCE_VERSION}
    - MAX_CRON_THREADS=${ODOO12_MAX_CRON_THREADS}
    - ODOO_BASE_URL=${ODOO12_ODOO_BASE_URL}
    - ODOO_QUEUE_JOB_CHANNELS=${ODOO12_ODOO_QUEUE_JOB_CHANNELS}
    - ODOO_REPORT_URL=${ODOO12_ODOO_REPORT_URL}
    - RUNNING_ENV=${ODOO12_RUNNING_ENV}
    - UNACCENT=${ODOO12_UNACCENT}
    - WORKERS=${ODOO12_WORKERS}

    networks:
      private:
    ports:
    - 8069:8069
    volumes:
    - odoo:/data/odoo
    - odoo-cache:/odoo/.cache

volumes:
  odoo:
  odoo-cache:
