FROM quay.io/acsone/odoo-bedrock:12.0-py35-latest

RUN set -e \
  && apt update \
  && apt -y install --no-install-recommends postgresql-client $BUILD_PACKAGE \
  && apt -y clean \
  && rm -rf /var/lib/apt/lists/*


# use this COPY for a regular docker build, otherwise use
# buildah bud --volume ${PWD}/release:/tmp/release
# or
# podmain build --volume ${PWD}/release:/tmp/release

COPY ./release /tmp/release

RUN pip install --no-index --no-deps /tmp/release/*.whl
